### ISSUE TITLE
[DOCUMENTATION] - Add Spanish translation

### ISSUE THREAD

**Issue by torrua** [torrua/keyboa#10]
**Is your feature request related to a problem? Please describe.**
There is no Spanish translation of Keyboa documentation

**Describe the solution you'd like**
Add Russian Translation to README-es.md file

**Comment by manueldose** [comment]
Hi! I can help with the Spanish translation. I am new to opensource. Do you need the translation of README.md?

**Comment by torrua** [comment]
Yes, it wil be perfect!

**Comment by torrua** [comment]
You can create a copy of README.md file and rename it to README-es.md

**Comment by manueldose** [comment]
ok great, i will work on it ;)

**Comment by manueldose** [comment]
hi again @torrua  I done a pr with the Spanish translation of the README, I hope everything works correctly. Any problem let me know. Thanks for letting me participate
