### ISSUE TITLE
(PYL-E0102) Function or method is being redefined

### ISSUE THREAD

**Issue by torrua** [torrua/keyboa#13]
## Description
A function, method or class is being redefined in the same scope. This would override the original definition, and doing this is strongly discouraged. Please verify that this is something that you intended to do.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/torrua/keyboa/issue/PYL-E0102/occurrences/](https://deepsource.io/gh/torrua/keyboa/issue/PYL-E0102/occurrences/)

**Comment by umairkarel** [comment]
Do we need to delete one?

**Comment by torrua** [comment]
No, just rename one of them accordingly.

**Comment by umairkarel** [comment]
We need to change function name right?

**Comment by torrua** [comment]
Right :) These 2 functions check different things, so it should be reflected in their names accordingly.
