### ISSUE TITLE
type object 'Union' has no attribute '__args__'

### ISSUE THREAD

**Issue by yerkimbekov** [torrua/keyboa#3]
Hi @torrua , thx for ur cool future!
I have some problem in the server, but in my machine it works

I have created markup
![image](https://user-images.githubusercontent.com/37952414/88341764-02750780-cd60-11ea-9a1e-c7b17707a0e3.png)

And server says that there is error:
`type object 'Union' has no attribute '__args__'`

Have you any ideas?

**Comment by torrua** [comment]
Hi, @yerkimbekov, thank you!
What version of python are you running on server?

**Comment by yerkimbekov** [comment]
> Hi, @yerkimbekov, thank you!
> What version of python are you running on server?

Python 3.5.2

**Comment by torrua** [comment]
Hmm... Type annotations should work starting from Python 3.5.
> And server says that there is error:
> `type object 'Union' has no attribute '__args__'`

Could you please post a complete listing of the error?
Are you using ```Union``` directly in your code somewhere?

**Comment by yerkimbekov** [comment]
> Hmm... Type annotations should work starting from Python 3.5.
> 
> > And server says that there is error:
> > `type object 'Union' has no attribute '__args__'`
> 
> Could you please post a complete listing of the error?
> Are you using `Union` directly in your code somewhere?

The error appears in this part of code: https://pastebin.com/raw/LpaMbYHa
![image](https://user-images.githubusercontent.com/37952414/88343652-b0ce7c00-cd63-11ea-9d3e-dc71d9ef1871.png)
No, I'm not using Union at all

**Comment by torrua** [comment]
Да, возможно, обновление версии поможет. Хотя всё должно работать и на 3.5 тоже. 
Я проверю это со своей стороны тоже.

И ещё - если не ловить исключения, то есть убрать блок try ... except ..., то в листинге будут подробности - в каком модуле, на какой строке произошла ошибка.

**Comment by yerkimbekov** [comment]
> Да, возможно, обновление версии поможет. Хотя всё должно работать и на 3.5 тоже.
> Я проверю это со своей стороны тоже.
> 
> И ещё - если не ловить исключения, то есть убрать блок try ... except ..., то в листинге будут подробности - в каком модуле, на какой строке произошла ошибка.

Я обновил до 3.7.8, и всё сработало;)

Anyway, если что вот ошибки
![image](https://user-images.githubusercontent.com/37952414/88344822-54b92700-cd66-11ea-9390-7059d33b59d9.png)

Спасибо, за обратную связь!

**Comment by torrua** [comment]
I hope I fixed it in 2.2.5 release ;)
